### ISSUE TITLE
does it support for indexing a n-dimension float vector?

### ISSUE THREAD

**Issue by ludlows** [kauppie/zorder#4]
hi,
thanks for making it open source.
I wanna use it index many n-dim float vectors.
does it support ?

**Comment by kauppie** [comment]
Floats themselves I don't think would work as indexes since they have non-linear representation. Are you just looking to cast/transmute between integers and floats? Or am I misunderstanding? Could you provide a code example of your use case or something else to better explain?

**Comment by ludlows** [comment]
Hi @kauppie ,
thanks for your reply.
is it possible to provice interface to index float coordiantes like [1.19,0.287,0.35]?

**Comment by kauppie** [comment]
You could probably do it like this:

```rust
pub fn index_of_f32<const N: usize>(array: [f32; N]) -> <u32 as Interleave<N>>::Output
where
    u32: Interleave<N>,
{
    let int_array = array.map(f32::to_bits);
    index_of(int_array)
}

pub fn index_of_f64<const N: usize>(array: [f64; N]) -> <u64 as Interleave<N>>::Output
where
    u64: Interleave<N>,
{
    let int_array = array.map(f64::to_bits);
    index_of(int_array)
}
```

I'm hesitant to bring functions like this into `zorder`, since they don't really form any Z-order curve structure due to their non-linearity. In other words, coordinates close in XYZ space are not close in the index space, which is the purpose of using Z-order curves for optimizations.

But you're free to use the example above in your own code if it satisfies you.

**Comment by ludlows** [comment]
thanks for providing code examples.
I am not familiar with the math under the space filling curves.
why a float coordinates close in XYZ space are not close in the index space ?

**Comment by ludlows** [comment]
another question is that the code seems unable to handle 10-D vector?
```rust
let index = index_of([255u32, 255u32, 255u32,267426u32,0u32,76u32,3675u32,34573u32,37583u32,37853u32]);
    |                 ^^^^^^^^ the trait `InterleaveOutput<10>` is not implemented for `u32`
```

**Comment by kauppie** [comment]
> thanks for providing code examples.
I am not familiar with the math under the space filling curves.
why a float coordinates close in XYZ space are not close in the index space ?

After playing with this [editor](https://www.h-schmidt.net/FloatConverter/IEEE754.html) I'm not so sure about the linearity thing anymore, because that was mostly based on a hunch. I thought for example, that 0.1 would produce a larger integer than 1, but that seems to be false. You'll just have to find out if it works for you. I also haven't seen Z-order curve being used directly with transmuted floats, as they are almost always integers or integers casted from floats (losing decimal part).

> another question is that the code seems unable to handle 10-D vector?

That's because it won't fit in `u128`, which is the largest integer type. For `u32` max would be 4D vector. You could use `u8` coordinates as those work up to 16D.

**Comment by ludlows** [comment]
thanks for your explanation.
is it possible to use `num_bigint::BigInt` in the future to support higher dimension  ?

**Comment by kauppie** [comment]
Maybe, but I'd rather use something which has statically allocated numbers for performance reasons.

What's your application for this crate anyway? Is performance your priority?

**Comment by ludlows** [comment]
I aim to use zorder to index a feature vector borrowed from a neural network. 
currently peformance is not considered as the first issue
